### ISSUE TITLE
Docker CLI / image option

### ISSUE THREAD

**Issue by pentatonicfunk** [php-parallel-lint/PHP-Parallel-Lint#133]
To allow to integrate it with CI directly, without installing it as dependency
similar to this: https://github.com/overtrue/phplint#docker-cli

so we can use it this way
```
          - step:
              image: overtrue/phplint:8.1
              name: PHP Linting parallel
              script:
                - /root/.composer/vendor/bin/phplint ./
```

**Comment by jrfnl** [comment]
@pentatonicfunk You can already get PHP Parallel Lint set up via the `setup-php` action, so I'm not sure what the point would be of adding more maintenance overhead ?

```yml
- name: Setup PHP without composer
  uses: shivammathur/setup-php@v2
  with:
    php-version: '8.2'
    tools: parallel-lint
- name: Run lint
  run: parallel-lint .
```
